### ISSUE TITLE
Add the ability to change the cropping frame size

### ISSUE THREAD

**Issue by RaedGhazal** [MoyuruAizawa/Cropify#17]
Currently, we can't change the cropping frame size, it is always centered with height and width equal to 
```kt
min(imageRect.width, imageRect.height) * 0.8
```

I would like to have the ability to either control this myself or at least have the option to choose the cropping frame initial size to be the full size of the image `height = imageRect.height, width = imageRect.width` instead of the centered square 

if I got some time I'd try to create a PR myself but I still need to figure out how to do it, if you know how and it's easy to perform quickly that would be really appreciated.

**Comment by MoyuruAizawa** [comment]
Thank you for the suggestion. It is possible by changing calculateFrameRect. In the composable function Cropify, I think it would be better to allow specifying the initial size (rather than specifying a numeric value, it would be better to specify whether it is full size or a certain percentage while maintaining the aspect ratio).

I do not plan to implement this myself. I am waiting for someone else to contribute.

**Comment by RaedGhazal** [comment]
@MoyuruAizawa I created a PR can you check it please?
